export enum WeaponType {
  AXE = 'axe',
  FIST = 'fist',
  HOE = 'hoe',
  PICKAXE = 'pickaxe',
  SHOVEL = 'shovel',
  SWORD = 'sword',
  SPEAR = 'spear',
  GREATSWORD = 'greatsword',
  KATANA = 'katana',
  TACHI = 'tachi',
  LONGSWORD = 'longsword',
  DAGGER = 'dagger',
  BOW = 'bow',
  CROSSBOW = 'crossbow',
  TRIDENT = 'trident',
  SHIELD = 'shield',
}
